name: Main
run-name: ${{ github.actor }} на Linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Используем Node.js, версия '${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Установка модулей и всех зависимостей
        run: npm install

      - name: сборка production проекта
        run: npm run build:prod

      - name: анализ кода TypeScript
        run: npm run lint:ts

      - name: анализ кода Scss modules
        run: npm run lint:scss

      - name: unit тесты
        run: npm run unit

      - name: сборка StoryBook
        run: npm run storybook:build

      - name: Публикация в Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
          exitZeroOnChanges: true